### ISSUE TITLE
Having trouble using concat! within unstringify!  Expecting `let`

### ISSUE THREAD

**Issue by randall-coding** [danielhenrymantilla/unstringify.rs#1]
Hi and thanks for making this very cool crate.  

I am having an issue making a simple macro.  I am making a macro that takes in an object identifier and a string and will output a function call using the string as the function/attribute call.  Here is what it looks like in theory 

`send!(struct, "foo")     // =>  struct.foo`

Seems simple right?  So within my macro, my idea was to just concat! the objects together into a string, then unstringify and voila!

    macro_rules! send {
        ($msg:expr, $obj:ident) => {
            unstringify!(concat!($obj, ".", $msg))
        }
    }

And my macro is being invoked simply with `let x = send!("hey()", test);`

I read through the documentation and I know it says concat! should work within unstringify! since you hard coded logic for that. But perhaps the logic is different than usual?  Any help is appreciate, thanks.

**Comment by danielhenrymantilla** [comment]
Hmm, have you tested with `stringify!($obj)` rather than `$obj` directly? Otherwise the `concat!` call won't work 🤔 

___

Also, if I have understood it correctly, another option is to implement `send` as:

```rust
macro_rules! send {( $msg:expr, $obj:ident $(,)? ) => (
    unstringify!( let $msg_unstringified = unstringify!($msg) in {
        $obj . $msg_unstringified
    })
)}
```

**Comment by randall-coding** [comment]
Thanks for the response.  Hmm, this could just be my ignorance of the finer points of macros in general.  

I think I tried that method before but I used `$obj.$msg_unstringified` with no spaces which yielded an error.  The space around the period is important I'm assuming?

I will test it out

**Comment by randall-coding** [comment]
Ah nevermind on one point.  I was not using `$obj.$msg_unstringified` I was using `$obj.$msg` and didn't use my new unstringified value.  Looks like the spaces don't matter (except for readability).

Perfect, that really saved me a lot of time.  I was so close but I don't think I was about to realize it.

**It works!**
